### ISSUE TITLE
Missing margins on demo

### ISSUE THREAD

**Issue by ProgramCrafter** [designervoid/ton-design-system#22]
Some elements have no or insufficient margin, for example "Cards" heading.
This reduces the impression of this design system.

**Comment by designervoid** [comment]
@ProgramCrafter used Spacings from the [Telegram Design System](https://www.figma.com/community/file/988466927624217947) (an unofficial pack of Telegram components) 
<img width="433" alt="image" src="https://github.com/systemdesigndao/ton-design-system/assets/43455658/39c784b9-96ee-4cbe-989a-ae54fe1f9334">

https://github.com/systemdesigndao/ton-design-system/commit/880dfac997f9504e961de3e992ea67a59710171f
https://github.com/systemdesigndao/ton-design-system-next-typescript/commit/5bf849cce4ac73bc3de4e35305a34d31576a0219

Thanks for proposal 👍 🥇
